# GitHub Actions Configuration for integrated testing using pytest
name: Test dbdicom

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install dbdicom
        run: |
          python -m pip install -e .
      - name: Test with pytest
        run: |
          python -m pip install pytest pytest-cov
          pytest --junitxml=junit/test-results.xml --cov=dbdicom tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ always() }}